// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package postgres

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, number, first_name, name, last_name, balance, created_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.FirstName,
		&i.Name,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

