// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Number    string `json:"number"`
	Password  string `json:"password,omitempty"`
	FirstName string `json:"first_name"`
	Name      string `json:"name"`
	LastName  pgtype.Text `json:"last_name"`
	Balance   int64
	CreatedAt pgtype.Timestamptz
}

type Payment struct {
	ID        int64  
	AccountID int64   `json:"account_id"`
	// can be positive and negative
	Amount    int64   `json:"cost"`
	Place     string  `json:"place"`
	CreatedAt pgtype.Timestamptz
}

